name: Verify
on:
    workflow_call:
    workflow_dispatch:

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - uses: actions/checkout@v3
              if: ${{ github.event_name == 'pull_request' }}
              with:
                  fetch-depth: ${{ github.event.pull_request.commits }} + 1
                  ref: ${{ github.event.pull_request.head.sha }}

            - uses: actions/checkout@v3
              if: ${{ github.event_name != 'pull_request' }}

            - name: Install dependencies
              uses: ./.github/actions/setup

            - name: Lint code
              run: pnpm --filter "...[HEAD~${{ github.event.pull_request.commits || 1 }}]" lint

    build:
        name: Build
        needs: lint
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - uses: actions/checkout@v3
              if: ${{ github.event_name == 'pull_request' }}
              with:
                  fetch-depth: ${{ github.event.pull_request.commits }} + 1
                  ref: ${{ github.event.pull_request.head.sha }}

            - uses: actions/checkout@v3
              if: ${{ github.event_name != 'pull_request' }}

            - name: Install dependencies
              uses: ./.github/actions/setup

            - name: Build
              run: pnpm --filter "...[HEAD~${{ github.event.pull_request.commits || 1 }}]" build

    types:
        name: Types
        needs: lint
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - uses: actions/checkout@v3
              if: ${{ github.event_name == 'pull_request' }}
              with:
                  fetch-depth: ${{ github.event.pull_request.commits }} + 1
                  ref: ${{ github.event.pull_request.head.sha }}

            - uses: actions/checkout@v3
              if: ${{ github.event_name != 'pull_request' }}

            - name: Install dependencies
              uses: ./.github/actions/setup

            - name: Check types
              run: pnpm --filter "...[HEAD~${{ github.event.pull_request.commits || 1 }}]" typecheck

    test:
        name: Test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              if: ${{ github.event_name == 'pull_request' }}
              with:
                  fetch-depth: ${{ github.event.pull_request.commits }} + 1
                  ref: ${{ github.event.pull_request.head.sha }}

            - uses: actions/checkout@v3
              if: ${{ github.event_name != 'pull_request' }}

            - name: Install dependencies
              uses: ./.github/actions/setup

            - name: Run tests
              uses: nick-fields/retry@v2
              with:
                  timeout_minutes: 20
                  max_attempts: 3
                  command: pnpm --filter "...[HEAD~${{ github.event.pull_request.commits || 1 }}]" test -- --coverage
